// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gpbzuhchxdlrbsievnst.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdwYnp1aGNoeGRscmJzaWV2bnN0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI1ODk4OTEsImV4cCI6MjA2ODE2NTg5MX0.qr5kAxwCq-ri9OHHO2TYZwc6F6d5MGgzWSAKVTsS7rA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});